# Generated by Django 5.0.3 on 2024-03-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fashion',
        ),
    ]
